### ISSUE TITLE
java version < 8 not supported?

### ISSUE THREAD

**Issue by joost-de-vries** [joost-de-vries/sbt-typescript#7]
```
[info] java.lang.UnsupportedClassVersionError: name/devries/sbt/typescript/JsonCleaner : Unsupported major.minor version 52.0
[info]  at java.lang.ClassLoader.defineClass1(Native Method)
[info]  at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
[info]  at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[info]  at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
[info]  at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
[info]  at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
[info]  at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
[info]  at java.security.AccessController.doPrivileged(Native Method)
[info]  at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
[info]  at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
[info]  at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
[info]  at name.devries.sbt.typescript.SbtTypescript$$anonfun$parseTsConfig$1.removeComments$1(SbtTypescript.scala:176)
[info]  at name.devries.sbt.typescript.SbtTypescript$$anonfun$parseTsConfig$1.parseJson$1(SbtTypescript.scala:182)
[info]  at name.devries.sbt.typescript.SbtTypescript$$anonfun$parseTsConfig$1.apply(SbtTypescript.scala:187)
[info]  at name.devries.sbt.typescript.SbtTypescript$$anonfun$parseTsConfig$1.apply(SbtTypescript.scala:173)
[info]  at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
[info]  at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
[info]  at sbt.std.Transform$$anon$4.work(System.scala:63)
[info]  at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[info]  at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[info]  at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[info]  at sbt.Execute.work(Execute.scala:237)
[info]  at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[info]  at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[info]  at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
[info]  at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
[info]  at java.util.concurrent.FutureTask.run(FutureTask.java:262)
[info]  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
[info]  at java.util.concurrent.FutureTask.run(FutureTask.java:262)
[info]  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
[info]  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
[info]  at java.lang.Thread.run(Thread.java:745)
[info] [error] (web-assets:typescript::jstaskJsOptions) java.lang.UnsupportedClassVersionError: name/devries/sbt/typescript/JsonCleaner : Unsupported major.minor version 52.0
```

**Comment by michaelvashchinsky** [comment]
@joost-de-vries, I had similar exception when creating new Play application.

In my case the `activator` had created Play v`2.5.4`, and has added several new to Play v`2.3.x` things to `plugins.sbt`, among them 

```
addSbtPlugin("org.irundaia.sbt" % "sbt-sassify" % "1.4.6")
```

When I have changed the Play version to `2.3.10` and  commented the line with `sbt-sassify` the exception had gone.

Hope it helps.

**Comment by joost-de-vries** [comment]
Huh. Thank you for letting me know. I've seen that issue only a few times and it made me worried.
I guess I can close this issue now.

Tx again!
